### ISSUE TITLE
Sign out is not working.

### ISSUE THREAD

**Issue by mmuller** [instedd/active-monitoring#46]
Version bba9f44

Reproduce steps:
Sign in.
Expand the user menu.
Click on `Sign out`.
Go back to the previous page.

Obtained:
The user is still signed in. 

http://recordit.co/HZXvf9FLdC

**Comment by matiasgarciaisaia** [comment]
Fixed by @emaraschio in #56

**Comment by mmuller** [comment]
The issue is still present in version 2c1feb1
See http://recordit.co/rHizNcdR5J

**Comment by emaraschio** [comment]
@mmuller fixed on staging

**Comment by mmuller** [comment]
Working properly in version 1d72f67
